### ISSUE TITLE
CSSPropertyOperations moved to react-dom

### ISSUE THREAD

**Issue by bsr203** [tajo/react-portal#103]
Hi,

I noticed that `CSSPropertyOperations` has been moved to `react-dom`. so only change needed for me was [at](https://github.com/tajo/react-portal/blob/master/lib/portal.js#L3)

`import CSSPropertyOperations from 'react/lib/CSSPropertyOperations';
`
to

`import CSSPropertyOperations from 'react-dom/lib/CSSPropertyOperations';
`

ref: https://github.com/facebook/react/issues/7770#issuecomment-253899837

**Comment by gaearon** [comment]
Please note that React does not officially support importing these modules at all. Instead of changing the path we encourage you to inline the code you rely on.

**Comment by hellatan** [comment]
i posted this comment in an [older issue](https://github.com/tajo/react-portal/issues/30#issuecomment-260983762), but I figured it would be better add it here instead:

this is an issue with react and the related packages bumping to 15.4.0 today.

I downgraded all of these packages:
```
npm install react@15.3.0 react-dom@15.3.0 react-addons-css-transition-group@15.3.0  react-addons-test-utils@15.3.0 react-addons-update@15.3.0
```

and this error went away.

**Comment by gaearon** [comment]
To be clear the issue is not with React. It is with libraries that import internal modules from React which was never supported. Please check out [the release notes](https://facebook.github.io/react/blog/2016/11/16/react-v15.4.0.html#separating-react-and-react-dom).

**Comment by daltones** [comment]
See #105

**Comment by tajo** [comment]
Yep, @gaearon is correct. This is not React's fault. All internal modules from React were removed, so future minor versions of React should not break this module. Thanks!

**Comment by gaearon** [comment]
Thanks for quick response!

**Comment by amitksingh1490** [comment]
for the temporary fix, I added below library in my dependencies "only-react-css-property-operations": "^1.0.1". It fixed the issue for now.
