### ISSUE TITLE
Cannot resolve module 'react/lib/CSSPropertyOperations'

### ISSUE THREAD

**Issue by Kudrik** [tajo/react-portal#107]
import CSSPropertyOperations from 'react/lib/CSSPropertyOperations';
Causing error with react 15.4.0
Error: Cannot resolve module 'react/lib/CSSPropertyOperations'

**Comment by lonelyclick** [comment]
+1

**Comment by sylvaingi** [comment]
This is discouraged by the React devs and using such internal libs will lead to more errors in the future. See https://twitter.com/dan_abramov/status/798926305030877184

**Comment by tajo** [comment]
It's fixed by `v3.0.0`. Please update. Thanks!
