### ISSUE TITLE
how to use button to close portal when set closeOnOutsideClick

### ISSUE THREAD

**Issue by qqnp1100** [tajo/react-portal#108]
```
<button
    onClick={() => this.setState({ show: !this.state.show })}
>click</button>
<Portal
      onClose={() => this.setState({ show: false })}
      isOpened={this.props.show}
      closeOnEsc
      closeOnOutsideClick >
     <div>...</div>
</Portal>
```

when i click button it will callback `onClose()`,it make `show `become false ,so i can't use this button to close portal when set `closeOnOutsideClick`.
is there anyone tell me how to solve it? thanks

**Comment by renanvalentin** [comment]
Have you tried to wrap the button and portal inside of a div?

**Comment by qqnp1100** [comment]
Can't put them in one portal.
i want make like this : 
![2016-12-09 8 45 22](https://cloud.githubusercontent.com/assets/14014255/21033539/fbfbfd14-bdeb-11e6-8fd6-64424c301f17.png)
click the button can open/close portal and click outside can close portal.

**Comment by tajo** [comment]
```
<Portal
      openByClickOn={<button>click</button>}
      closeOnEsc
      closeOnOutsideClick >
     <div>...</div>
</Portal>
```

Don't use `isOpened` and other props at the same time. It's controlled vs uncontrolled approach, not the both at same time.

**Comment by qqnp1100** [comment]
Thank you. I'll try to use it.
