### ISSUE TITLE
Position logic in container ?

### ISSUE THREAD

**Issue by moak** [tajo/react-portal#111]
Hi, I see that the logic for the AbsolutePosition component is handled in the container, with the setState method on onClick. I am still new in React and I was wondering how we could put this logic outside the container and maybe more in the Portal component with refs ? The objective would be to manage "positions" for AbsolutePosition like "left", "top-right", etc..

Tell me what you think and if what I say sounds doable. 

Thank you

**Comment by oyeanuj** [comment]
@moak Do you mean, position like tooltips?

**Comment by oyeanuj** [comment]
@tajo Is there an example or a recipe of using react-portal for tooltips? I think, that would also answer the above question.
