### ISSUE TITLE
className in 3.0.0

### ISSUE THREAD

**Issue by imjohansunden** [tajo/react-portal#112]
What I can see react-portal isn't applying classNames in version 3.0.0, but it did in 2.2.1. Is this something that will change or should I update my code to add my classes to a element of my own?

**Comment by slorber** [comment]
@imjohansunden I'm going to submit a PR for that because I need it too, see https://github.com/tajo/react-portal/pull/105

**Comment by slorber** [comment]
As it seems people do not agree on putting back className support in 3.0.0, please manifest yourself if you want that feature back.

You can also temporarily use my fork that backports the className (not styles) features:

    "react-portal": "https://github.com/slorber/react-portal.git#build",

**Comment by tajo** [comment]
It was discussed here https://github.com/tajo/react-portal/pull/105 ... Please use extra divs. Sorry for the inconvenience!
