### ISSUE TITLE
Allow to disable passing the "closePortal" hook

### ISSUE THREAD

**Issue by slorber** [tajo/react-portal#114]
Hi,

Please consider the case:

```
      <Portal isOpened={true} className={"toast-portal"}>
        <ReactCSSTransitionGroup
          component="section"
          className={"toast"}
          transitionName="toast-transition"
          transitionEnterTimeout={1000}
          transitionLeaveTimeout={1000}>
          {this.renderToasts()}
        </ReactCSSTransitionGroup>
      </Portal>
```

As ReactCSSTransitionGroup is not a simple dom element, it gets passed the "closePortal" callback.
Unfortunatly, I do not own the code of ReactCSSTransitionGroup and it actually forwards all its props to the underlying component (section here), so the section element receive the closePortal callback and React >= 15 is unhappy about that.

As a workaroud I'll create an intermediate element, but it could be useful to be able to disable this callback, at least if there's no "onClose" callback passed as props and it's the noop default callback (as of current implementation it's not really practical to distinguish noop callback to user-provided callback)

**Comment by tajo** [comment]
> at least if there's no "onClose" callback passed as props and it's the noop default callback (as of current implementation it's not really practical to distinguish noop callback to user-provided callback)

I don't fully understand this part. Can you formulate it differently?

I know you hate an extra `div` but imo it's better than extra API.

**Comment by slorber** [comment]
> at least if there's no "onClose" callback passed as props and it's the noop default callback (as of current implementation it's not really practical to distinguish noop callback to user-provided callback)

I just mean that in current implementation with onClose being set to an empty function, there's no easy way to detect presence or absence of user-provided onClose callback.


---------------------------------------------------

@tajo this is not really related to the className problem

Suppose I have this:

 ```
<Portal isOpened={true} className={"toast-portal"}>
        <ReactCSSTransitionGroup component="section">
            <div>Something</div>
        </ReactCSSTransitionGroup>
</Portal>
```

- ReactCSSTransitionGroup is library code I don't own and I can't modify it
- ReactCSSTransitionGroup is not a native DOM element
- ReactCSSTransitionGroup creates an intermediate element (here "section") and forwards all its props
- Portal passes down "closePortal" func to non-native DOM element childrens (current case)
- React 15 is unhappy if section element receives a "closePortal" prop


I don't know what is the best solution to this problem, just saying it can be annoying that the portal always pass down the closePortal callback to non-native children elements. It is really just a React warning problem, nothing else.

The following would work fine, but it's a lot of extra html elements in the end, and I don't really like the idea of introducing either an extra useless div just to avoid a React warning

 ```
<Portal isOpened={true} className={"toast-portal"}>
   <div>
        <ReactCSSTransitionGroup component="section">
            <div>Something</div>
        </ReactCSSTransitionGroup>
     <div>
</Portal>
```


This solution is less idiomatic but it works fine:


 ```
<Portal isOpened={true} className={"toast-portal"}>
        <ClosePortalFilteredReactCSSTransitionGroup component="section">
            <div>Something</div>
        </ClosePortalFilteredReactCSSTransitionGroup>
</Portal>

const ClosePortalFilteredReactCSSTransitionGroup  = ({closePortal,children,...props}) => (
        <ReactCSSTransitionGroup {...props}>
            {children}
        </ReactCSSTransitionGroup>
)
```

**Comment by mathieumg** [comment]
Agnostic version:

```js
const NoClosePortalProp = ({closePortal, children,...props}) => React.cloneElement(
  children,
  props,
);

<NoClosePortalProp>
  {/* something here */
</NoClosePortalProp>
```

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
