### ISSUE TITLE
isOpened seems to still exist in 3.0

### ISSUE THREAD

**Issue by TheSavior** [tajo/react-portal#126]
When looking at the commit for version 3.0, it looks like the prop in the code is still `isOpened` and wasn't changed to `isOpen`. Am I looking in the wrong place or is this not correct?

https://github.com/tajo/react-portal/blob/dee11f89fb180b9bffaa92ca312a033bcc88b254/lib/portal.js#L31

**Comment by tajo** [comment]
Yep, it hasn't been changed. I am now thinking about remove it completely (https://github.com/tajo/react-portal/issues/121).

**Comment by vertaxe** [comment]
I lost 10 minutes trying to figure out why isOpen wasn't working:

"Oh. It's actually isOpened..."
