### ISSUE TITLE
Behaivor onClose in nested Portal

### ISSUE THREAD

**Issue by Thisman** [tajo/react-portal#129]
I have the same code

```
<Portal>
    <div>
        <Portal> </Portal>
    </div>
<Portal>
```

Then i click outside child portal, the parent portal is closed too. How can i close only child Portal, but not Parent. For example we can throw event object to onClose callback to use `e.stopPropagation()`, this might resolve this problem

In my case: i have `CustomSelect` in which i use `Portal` for options, and i can't use the `CustomSelect` in other `Portal`

**Comment by Thisman** [comment]
I had cloned repo and had tried understand the problem: `document click` event fired on parent portal first, then on child one, that's why parent portal closed first. Don't know is it real to check if portal has child portal don't close before all child ones didn't closed

**Comment by tajo** [comment]
You should handle the state manually by setting `isOpened` to true/false. The built-in state handling (with closeOnOutsideClick) covers just basic use-cases.
