### ISSUE TITLE
Portal contents remain in DOM when mounting and unmounting with isOpen very quickly

### ISSUE THREAD

**Issue by lencioni** [tajo/react-portal#137]
I have some code that renders a portal with `isOpen` and then immediately unmounts it. When this happens, I noticed that the contents of the portal stay on the DOM, even though the component has unmounted.

Taking a glance at the code, it seems that this happens because `openPortal` calls `this.setState` followed by `this.renderPortal`. 

https://github.com/tajo/react-portal/blob/7b24765b6a77862495ceb843dd1cbdad1ae0284f/lib/portal.js#L78

Then, when the portal unmounts, it calls `this.closePortal` which checks to see if the state is active and if it is it cleans up the DOM.

https://github.com/tajo/react-portal/blob/7b24765b6a77862495ceb843dd1cbdad1ae0284f/lib/portal.js#L95

However, `this.setState` is asynchronous, so these aren't always going to be in sync.

It might be a good idea to refactor this to implement `componentDidUpdate()` to call `this.renderPortal` and `this.closePortal` when necessary in response to state/props changes instead of calling it synchronously.

**Comment by dwick** [comment]
#124
