### ISSUE TITLE
openByClickOn element does not toggle portal open state correctly

### ISSUE THREAD

**Issue by islemaster** [tajo/react-portal#140]
This issue is easily reproduced on `react-portal`'s [own demo page](https://miksu.cz/react-portal/).

1. Click the "Another Portal" button.  The portal opens.
2. Click the "Another Portal" button again.
   Expected: The portal closes, because the click was "outside" the rendered portal.
   Actual: The portal remains open.

_(Tested on Google Chrome 56.0.2924.87 (64-bit) Ubuntu 16.04.)_

This problem occurs for portals using the `openByClickOn` and `closeOnOutsideClick` properties, as [the portal on the demo page does](https://github.com/tajo/react-portal/blob/4b7c4c2385272bc945f9effbde3b743940d0c1f2/examples/index.js#L110-L114).

Though it's not clear from the documentation whether the current behavior is by design, I'd argue that it's not (or shouldn't be) for two reasons:

One, it's a fairly common UI convention for a button that opens a menu to be able to subsequently close it (see GitHub's "add" and "user" menus).

Two, nothing in the current implementation suggests this was intended behavior.  In fact, you can set breakpoints and see that clicking the `openByClickOn` element will enter the [`handleOutsideMouseClick`](https://github.com/tajo/react-portal/blob/master/lib/portal.js#L106-L114) method, continue into [`closePortal`](https://github.com/tajo/react-portal/blob/master/lib/portal.js#L82-L104) and actually close the portal for just a moment - but immediately afterward [`handleWrapperClick`](https://github.com/tajo/react-portal/blob/master/lib/portal.js#L70-L75) fires leading to [`openPortal`](https://github.com/tajo/react-portal/blob/master/lib/portal.js#L70-L75) so the attempt to close the portal effectively fails.

The root cause seems to be a failure to stop propagation of the click event, [as attempted here](https://github.com/tajo/react-portal/blob/master/lib/portal.js#L112). It might have something to do with the fact that the 'outside click' being handled is a native event, not a React [`SyntheticEvent`](https://facebook.github.io/react/docs/events.html).  I'm not sure what the solution is though - I hate to throw `preventDefault` around but maybe it'd do the trick here?

**Comment by tajo** [comment]
Agree that better UX would be to close. Will look into it.

**Comment by tajo** [comment]
Hey, please check the new major version of react-portal:  https://github.com/tajo/react-portal/issues/157

**It's React v16 only since its uses the new official Portal API**. There is the first beta released and I would like to get your feedback. I don't have bandwidth to maintain v3 which is very different and full of hacks. 

I am happy to discuss this with v4 in mind. If this is still a problem, please re-open/update the issue. Thanks.
