### ISSUE TITLE
Append to element other than document.body

### ISSUE THREAD

**Issue by Matt-Butler** [tajo/react-portal#141]
Some other portal libraries allow consumers to append elements other than document.body.

For example, [react-aria-modal](https://github.com/davidtheclark/react-aria-modal) allows a consumer to [provide an applicationNode](https://github.com/davidtheclark/react-aria-modal#applicationnode) using the [react-displace package](https://github.com/davidtheclark/react-displace).
This allows for improved accessibility for components that use react-portal.

Thank you!

**Comment by Hypnosphi** [comment]
Looks like a duplicate for #99, which was closed a bit prematurely =(

**Comment by tajo** [comment]
Will. It's tracked in multiple PRs already. Closing it here.
