### ISSUE TITLE
ESC key closes all modals

### ISSUE THREAD

**Issue by winkler1** [tajo/react-portal#143]
We're using this for modal dialogs and sometimes need to do modals off of modals (mea culpa).

Problem: When the 2nd modal is open and you type ESC, both modals are closed.

I've tried changing `handleKeyDown` in `build/portal.js` to stop propagation, but nothing has worked :) - 
```
key: 'handleKeydown',
    value: function handleKeydown(e) {
      if (e.keyCode === KEYCODES.ESCAPE && this.state.active) {
        e.preventDefault();
        e.stopPropagation();
        this.closePortal();
        return false;
      }
    }
```

**Comment by Hypnosphi** [comment]
Are you using `closeOnEsc` on both portals? In this case, maybe you shoud leave it only for the innermost one

**Comment by winkler1** [comment]
Yes, the user expects to be able to ESC out of each dialog (independently).

**Comment by Hypnosphi** [comment]
Then you should handle it manually, at least in the case of parent dialog
