### ISSUE TITLE
Function as children

### ISSUE THREAD

**Issue by chbdetta** [tajo/react-portal#160]
What about adding the support for function children so codes below can be valid
```js
<Portal openByClickOn ={<a>test</a>}>{(closePortal) => (
  <Modal>
    {/*some content*/}
    <button onClick={closePortal()}>close me</button>
  </Modal>
)}</Portal>
```
I could just inline the portal content without creating a component class / stateless functional comp to use the `closePortal`

**Comment by tajo** [comment]
Yes. This is a great pattern and I will use it.

**Comment by tajo** [comment]
Used in https://github.com/tajo/react-portal/issues/157
