### ISSUE TITLE
plans re: React v16

### ISSUE THREAD

**Issue by macgyver** [tajo/react-portal#163]
This is a great project that has shaped and informed the development of the ecosystem, which is evidenced by convergent evolution for other frameworks, e.g. https://github.com/LinusBorg/portal-vue and https://github.com/yapplabs/ember-wormhole, and now with the introduction of portals as a core feature in React v16.
 
Just curious, what is the future of the `react-portal` package?

**Comment by tajo** [comment]
**So my plan is to significantly simplify this library (there is already some code in master)**. Having only basic minimalistic wrapper for `createPortal` that will handle server side rendering and by default appends portal into `document.body` (with an option to specify your own node). I think that's still quite useful and covers 90% of use-cases.

I am still not sure if it's valuable to keep/develop stateful version of portal. It's nice for some basic use-cases but people tend to overuse it, asking for various life-cycle hooks while they should be rather using stateless version and implement whatever they need around it.

Opinions welcome!

**Comment by tajo** [comment]
Obviously this library is pretty popular (over 300k downloads/month) so I don't want to cause a crisis but some major changes are needed.

**Comment by tajo** [comment]
Check:  https://github.com/tajo/react-portal/issues/157
