### ISSUE TITLE
Enzyme doesn't support Portals

### ISSUE THREAD

**Issue by tajo** [tajo/react-portal#171]
Currently, enzyme doesn't support new Portal API.

- https://github.com/airbnb/enzyme/pull/1263
- https://github.com/airbnb/enzyme/issues/1150

That makes writing tests harder. So far, I've added tests for `<Portal />` since it's pretty trivial but will wait for enzyme with `PortalWithState` tests.

**Comment by ranneyd** [comment]
@tajo have you looked at https://www.npmjs.com/package/enzyme-adapter-react-16

**Comment by tajo** [comment]
@ranneyd Yes. I even put it into [test setup](https://github.com/tajo/react-portal/blob/master/testSetup.js#L2) already but it just doesn't work with Portals. Yet.
