### ISSUE TITLE
Re-rendering unnecessarily?

### ISSUE THREAD

**Issue by Ganasist** [tajo/react-portal#195]
I've been optimising across my app recently using ["why-did-you-update"](https://github.com/maicki/why-did-you-update)

It's triggering on react-portal quite a bit:

![screen shot 2018-01-24 at 17 05 55](https://user-images.githubusercontent.com/2892647/35342653-decbe6ce-0128-11e8-8e3c-400d5b52a5c3.png)

Is there any way you could optimise this via PureComponent or shouldComponentUpdate?

**Comment by tajo** [comment]
Do the optimization in a parent / child component?
