### ISSUE TITLE
this.portal is null on IE11 - handleOutsideMouseClick()

### ISSUE THREAD

**Issue by hinok** [tajo/react-portal#197]
Hey,
We have a case in one of our applications where this error appears only on IE 11. It doesn't appear on any other browser and it's quite hard to debug on IE11 🗡 

The quickest fix is to check if `this.portal` exists, @tajo what do you think?
Beside that even if this error is reported, everything seems to work correctly.

![screen](https://user-images.githubusercontent.com/1313605/35803063-c07c1362-0a72-11e8-968b-8a3a919c5b69.png)

I can prepare PR if you want.

**Comment by tajo** [comment]
@hinok Yes. PR would be great!

**Comment by v1adko** [comment]
I'm having the same issue, but not on IE.
Maybe the issue is with the usage of the component `PortalWithState`.
In my use case I've wrapped a portal with a fullscreen backdrop and I can't close the modal on outside click due to this error.

**Comment by odelijairo** [comment]
Hello @tajo could you check the PR?
