### ISSUE TITLE
ReactPortal with React15.x not removing child

### ISSUE THREAD

**Issue by shahankit** [tajo/react-portal#198]
I'm using react-portal with react 15. As per the doc I followed this to toggle contents of portal but with custom node:
```jsx
{isOpen && <Portal node={this.customNode}>Sometimes portaled?</Portal>}
```

Because of this when isOpen is false, the portal node is not removed from dom. This issue is because of [this](https://github.com/tajo/react-portal/blob/master/src/LegacyPortal.js#L18) condition in LegacyPortal.js. Is there any specific reason that passing a custom node requires to manage toggling content of portal manually. I checked the default reactDom.createPortal does not require so, because running the same code in React 16 works.

**Comment by tajo** [comment]
Oh, I guess we should do this for both Legacy portal.

```js
componentWillUnmount() {
  ReactDOM.unmountComponentAtNode(this.props.node || this.defaultNode);
  if (this.defaultNode) {
    document.body.removeChild(this.defaultNode);
  }
  this.defaultNode = null;
  this.portal = null;
}
```
Since we want to unmount the child it but preserve the original custom node.

**Comment by tajo** [comment]
@shahankit It that makes sense, a PR with test would be very appreciated!

**Comment by shahankit** [comment]
Hi @tajo I've added a pull request here: https://github.com/tajo/react-portal/pull/199
