### ISSUE TITLE
Other portal targets?

### ISSUE THREAD

**Issue by netsgnut** [tajo/react-portal#20]
Currently the package only allows the portal target to be `document.body`, which is useful for e.g. modals, loading bars and so. However, if we can allow the target to be specified individually it can also be useful for other use cases, for instance integrating with other rendering libraries where the target DOM may not be registered on React.

Any ideas?

**Comment by tajo** [comment]
What are the other use-cases than DOM? The whole point of this "hack" is to prevent application of non-related CSS rules to our modals, loading bars ...etc.

**Comment by netsgnut** [comment]
It is mostly about the DOM hierarchy here. The use case here is that the React rendering hierarchy can be different than the actual DOM, where the target DOM node may not be in direct control in React.

For instance, take [Leaflet](http://github.com/leaflet/leaflet) as an example. It is a library that [provides DOM manipulation functions for its internal use as well as plugins](https://github.com/Leaflet/Leaflet/tree/master/src/dom). Currently even if we are [to use a React binding on it](https://github.com/PaulLeCam/react-leaflet), the DOM objects are still managed by the library itself. Let's say, there is an overlay control on the map that is instantiated and created by the Leaflet library, but would like the content to be powered by React. It can be useful if the rendering is "redirected" somewhere.

---

That said as I read the source more carefully yesternight, it seems what I need is a stub class that does `React.render(React.cloneElement(props.children), this.redirectedNode)` whenever `componentWillMount(props)` or `commentWillReceiveProps(props)` while rendering nothing. That should already satisfy the not-quite-visual bits of requirements here.

Probably I should make a simplified fork of this library and name it like `react-basic-portal` or so ;)

**Comment by tajo** [comment]
Um, I see ... well if you can somehow integrate it into current library, please open a PR instead of forking. Thank you.

**Comment by netsgnut** [comment]
Agreed, although I am not entirely sure what to do. While I still use `react-portal` for modals in my projects and I think it will stick around, I just think given such a broad and generic name "portal" I just *guess* it would be nice to make it work a bit more generic. In my projects, I make a simplified fork of `react-portal`, which is essentially just a trimmed-down version of your Portal implementation and let them sit to each other.

The core essence of the whole Portal thing to make it work is to `openPortal` whenever `componentWillMount` and `componentWillReceiveProps`, and what opening portals does is `React.render(React.cloneElement(props.children), this.node);`.

If you like, I can make a PR and I could make the aforementioned simplified class (only ~50 lines of code actually) called `BasicPortal` or so and place at `lib/basic-portal.js` or so. Would you like that though? Thanks.

**Comment by nickcolley** [comment]
Could just make a prop called 'target' and just append to that rather than document.body maybe?

**Comment by tajo** [comment]
react-portal depends on react-dom because of `ReactDOM.unstable_renderSubtreeIntoContainer` function), so the prop `target` wouldn't help to solve @netsgnut issue, right?

@nickcolley Is there any use-case when you need to create a subtree in other place than document.body? If so, I am not against the `target`.

Am I missing something?

**Comment by netsgnut** [comment]
As mentioned before I am not quite sure if my case is one of the use cases what @tajo wants `react-portal` to cover. But I am happy to share what I have done here for my case.

The implementation that I currently use introduces an outlet that "tags" a target with a particular name, e.g. `<TargetOutlet name="sidebar" />`. The name reference can later be targeted with a portal, e.g. `<Portal target="sidebar" />`. The trick here is that whenever a `TargetOutlet` is instantiated, it updates an internal global reference table that manages the DOM target and the target name, that allows the portal to redirect the rendering to the appropriate target.

I would really love to hear if there are other devs out there face a similar (which I believe is niche) use case, and what their solutions are, too.

**Comment by thedamon** [comment]
I'm in a situation wishing there was a target-prop!

When building a React component that is embedded on an already existing page but we don't have easy access to update existing markup, but we would like to be able to bring up some messages etc in specific places WRT to the structure of the existing site.

**Comment by thedamon** [comment]
@netsgnut does your fork have that functionality?

**Comment by netsgnut** [comment]
@thedamon May I ask if the reference of your target element gets changed over time?

**Comment by thedamon** [comment]
No it wouldn't.
We've got around there issue differently though

**Comment by meandmax** [comment]
@thedamon, can I ask how your workaround actually works. We are in a situation needing a differen target, and it seems for me that a prop "target" would solve that?

**Comment by tajo** [comment]
I am not against the (optional) prop target if it solves your issues. Just saying, in general, you should avoid creating new React subtrees if possible. There is one legit exception: modals, loading bars, popups that need to be rendered in document.body, so they can be properly (independently) positioned and styled. 

You could still avoid using this library, but then you would have to render modal (or popup...) in one place (root component) and control it or send it there some content (and by content I mean only plaintext) through a different (probably deep nested) component. 

That goes against basic React component concept - keep dependent stuff in one place. This library makes this task very convenient but it's still a hack. That's why I am not sure why you need to/want to target anything else then document.body.

**Comment by thedamon** [comment]
@meandmax this was in an unused design so we never really ended up having to deal with the problem so unfortunately i can't help!
