### ISSUE TITLE
How to enable SSR of portaled content?

### ISSUE THREAD

**Issue by al4str** [tajo/react-portal#205]
I use simple `<Portal><Modal /></Portal>` to render my modals. 
But can't see it rendering in `view-source` tab.

Something missing in the docs?

**Comment by 7rulnik** [comment]
@al4str currently it's not supported because of https://github.com/tajo/react-portal/blob/master/src/Portal.js#L15

But I have some ideas how we can make it work

**Comment by al4str** [comment]
@7rulnik I understand.
But why it is still mentioned in [README](https://github.com/tajo/react-portal/blame/master/README.md#L17) ?

**Comment by 7rulnik** [comment]
@al4str seems that it's should be deleted for now. You can send PR.

**Comment by tajo** [comment]
Fair enough. It would be better to say: "It doesn't break SSR". Portal is expecting DOM node as a target, so it's not really possible to SSR it?

**Comment by 7rulnik** [comment]
@tajo what are you thinking about this approach?
https://michalzalecki.com/render-react-portals-on-the-server/

**Comment by tajo** [comment]
@7rulnik Yea, the solution makes sense but the "why" doesn't really resonate with me. Portals are (almost) always hidden on the initial load.

@al4str The whole point of portals it to render components to a different scope (a new react tree). Why would we render them in-line during the SSR?

**Comment by 7rulnik** [comment]
@tajo I think it can be edge-case with hash in url. For example https://domain.com/page#popup

**Comment by mherodev** [comment]
Ah, is this why I'm seeing the error `Warning: Expected server HTML to contain a matching <div> in <header>.` when trying to render my portal? 

When I revert to `react-portal@3` this error goes away and the portal continues to work, so I'm doing that for now. (although having to pass in `isOpened` is a little clunky)
