### ISSUE TITLE
Add nodeID and nodeClassName props to Portal

### ISSUE THREAD

**Issue by fandrupaw** [tajo/react-portal#210]
it would be great to have `nodeID`  and `nodeClassName` props that will be passed into created `div`

```
<Portal nodeID="fooId" nodeClassName="foo-class">
  ....
</Portal>

--------

<body>
  ...
  <div id="fooId" class="foo-class">...</div>
</body>
```

**Comment by tajo** [comment]
Why you can't just delegate those on your own (inner) div?

**Comment by fandrupaw** [comment]
cuz as u wrote this will be an inner div, from css perspective it makes difference. 

this
```
<body>
...
  <div>
    <div class="foo"></div>
  </div>
</body>
```

 is not equal to this

```
<body>
...
  <div class="foo">
    <div>...</div>
  </div>
</body>
```
