### ISSUE TITLE
Getting "Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `Modal`."

### ISSUE THREAD

**Issue by shaharyakir** [tajo/react-portal#24]
After having upgraded to 1.1.0 and react 0.14.

Only thing that solved it for me was by looking here https://www.reddit.com/r/reactjs/comments/3m8apr/a_quick_intro_into_simple_stateless_components_in/

And changing exports['default']... to module.exports

**Comment by tajo** [comment]
Stateless functions are meant just for simple components like buttons. Do you try to put there `<Portal />`? Code example?

**Comment by nickcolley** [comment]
Yeah I had to do the following: 
```js
var Portal = require('react-portal').default;
```

**Comment by theogravity** [comment]
Thanks, doing the `.default` worked for me

**Comment by Darwesh27** [comment]
What to do when using ES6?

**Comment by pjehan** [comment]
With ES6 you could use this syntax:
`import {default} as Portal from 'react-portal`

**Comment by phsantiago** [comment]
```
./src/components/ContactForm/ContactForm.jsx
Syntax error: default is a reserved word (2:8)

  1 | import React, {Component} from 'react';
> 2 | import {default} as Portal from 'react-portal'
    |         ^
```
I've got this
