### ISSUE TITLE
Using the scroll bar dismisses the modal.

### ISSUE THREAD

**Issue by Nickersona** [tajo/react-portal#26]
Not sure if this is the intended behaviour but I have a use case where we want to be able to scroll without dismissing the modal.  I'm wondering if this should be configurable through props or just a default behaviour.  Let me know and I can create a pull request.

**Comment by tajo** [comment]
Interesting. Is there something that needs to be changed to enable this use-case? I believe it's out of react-portal scope.

**Comment by Nickersona** [comment]
It's a one line fix, in the handleOutsideMouseClick method, line 125:

    if (isNodeInRoot(e.target, findDOMNode(this.portal)) || e.target.nodeName === 'HTML') { return; }

The `e.target.nodeName === 'HTML'` returns true only when the scrollbar is clicked. I checked it back to IE9.  I feel like this is in scope given that it's part of the modal dismissal behaviour.

I feel that, given it's possible to scroll with the mouse wheel with the portal open, then scrolling with the scrollbar should work as well.

**Comment by tajo** [comment]
`closeOnOutsideClick = true` but except the scrollbar? That's not very intuitive for the user, right? Modals should be handled (closed) before further interaction with underlying page (e.g. new post modal at twitter.com). If you need to interact with the background, set `closeOnOutsideClick = false` and do what you need to do.

**Comment by aveline** [comment]
If the modal has a lot of content causing it to extend below the screen, the user should be able to scroll down to view the additional modal content with the scroll bar.

**Comment by tajo** [comment]
I see. @Nickersona still down for a PR?

**Comment by Nickersona** [comment]
Sure! I'll get to it in then ext day or 2

**Comment by tajo** [comment]
Merged and published as `v1.3.0`: https://github.com/tajo/react-portal/pull/27

**Comment by tajo** [comment]
I had to remove it (`v2.1.0`), because it introduced this bug https://github.com/tajo/react-portal/issues/49. That has bigger priority. If you know about some better workaround for ignoring scrollbars let me know.

**Comment by silvenon** [comment]
I think it's better to leave this up to the user. A good way to do it is to add a `<div>` in the background which stretches over the whole screen, so clicking on it would dismiss the portal. Its styling would depend from UI to UI, so I don't think it's possible to write a generic one in this library.

It's better to remove this functionality than to have an implementation which doesn't work correctly.
