### ISSUE TITLE
Animating a portal on close.  

### ISSUE THREAD

**Issue by Nickersona** [tajo/react-portal#29]
Is there a suggested strategy to animate out a portal before it's removed from the DOM? Or should this be handled by a container component?

I think this ideally would be handled by a beforeClose callback that can trigger removing the node and reseting the portal state after it's been executed.

**Comment by tajo** [comment]
I don't use animations with react-portal. Anybody else? 

Anyway, I open to `beforeClose` callback if necessary. Can you create a PR and example of usage with some animation?

**Comment by Nickersona** [comment]
PR is here: https://github.com/tajo/react-portal/pull/33. Had to also implement an onOpen callback to handle the animate in functionality.   Let me know your thoughts.  

With this implementation it's possible to call a close event, provide a beforeClose callback that doesn't trigger resetPortalState(), and have the close event not actually close the portal.  But given that the beforeClose event can by async, (animation, ajax fetch, whatever) I don't really see a way to enforce that the callback closes the Portal.
