### ISSUE TITLE
Test specs

### ISSUE THREAD

**Issue by PeteJodo** [tajo/react-portal#32]
Every good lib should have specs! :smile: 

Personally, I'm actually not quite sure how to go about testing something like this. How would you get a ref to the portal?

**Comment by TheSavior** [comment]
I'd also love for this library to have tests. 

In regards to your question about getting a ref to the portal, if you have:

```
<ReactPortal ref="portalElement"><div>MyContent</div></ReactPortal>
```

you can do:

```
this.refs.portalElement.portal
```

https://github.com/tajo/react-portal/blob/master/lib/portal.js#L83

**Comment by tajo** [comment]
I agree! [This library](https://github.com/airbnb/enzyme) could help. Anyone wants to investigate it?

**Comment by PeteJodo** [comment]
I'll probably be looking into it either next week or sometime in January. Have been pretty busy. That's a DOM-less testing utility? I've been looking for one other projects. The shallow-renderer in React/addons/TestUtils leaves much to be desired

**Comment by PeteJodo** [comment]
Oh nice it supports both and you can simulate clicks, etc on shallow renderings. This looks super useful

**Comment by PeteJodo** [comment]
@tajo do you think we can get by with just shallow rendering (and no DOM) or should I include jsdom. I'll be starting this today

**Comment by tajo** [comment]
merged: https://github.com/tajo/react-portal/pull/37
