### ISSUE TITLE
What is the reason behind NPM 3+ request?

### ISSUE THREAD

**Issue by operatino** [tajo/react-portal#34]
Hi,

I'm wondering why preferred NPM version for the package is defined to 3+? It should not make any difference for the component if it was installed by NPM 2 or 3.

And I didn't noticed any problems using it within NPM 2 env.

**Comment by tajo** [comment]
Good point. I removed it. Still, I would recommend to switch to NPM3+ and Node4/5 asap.

**Comment by operatino** [comment]
@tajo what's the reason to switch to NPM 3? It's slow as hell :)

Also latest Node 4.x is enterprise ready and have long term support, and it still comes with NPM 2

**Comment by tajo** [comment]
My fav: Fixes some bugs with shrinkwrap + automatically updates it. It works better with Windows (the flat structure).
