### ISSUE TITLE
Portal.onOpen() bug

### ISSUE THREAD

**Issue by john-osullivan** [tajo/react-portal#35]
Hey, this seems like a pretty straightforward bug, although I'm not sure the best way to fix it.  Currently, the onOpen callback isn't firing.  When I looked into it further, I found that while the `openPortal` method in `lib/portal.js` calls `this.props.onOpen`, the same method in the main `portal.js` file does not.  The lines are simply missing.  According to the commits the main file hasn't changed in two months, so maybe the source was updated but the project wasn't rebuilt.  

Whatever it was, I fixed it on my local copy by manually adding:
```
      if (this.props.onOpen){
        this.props.onOpen(this.node);
      }
```
to the end of the `openPortal` method in the top-level `portal.js`.  Thought I'd let you know the issue was there, even if I'm not certain of the right way to fix it with a PR.

**Comment by tajo** [comment]
Fixed and released as `v1.4.1`. Thanks!
