### ISSUE TITLE
Bug on open/close: Invariant Violation: removeComponentAsRefFrom(...)

### ISSUE THREAD

**Issue by john-osullivan** [tajo/react-portal#38]
Hello again,

I'm not sure what changed, but the code I had which was previously working no longer does.  The React-Portal I have opens correctly, but it renders the modal inside of it too far down on the page.  Additionally, and more importantly, when I try to click out of it or hit `esc`, I get this error:
```
Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. You might be removing a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
```
I'm reasonably sure that I don't have two copies of React loaded.  One key thing here is that I'm using React with Meteor and Webpack, so my React is coming from an "external" package.  Is there a chance that react-portal is trying to instantiate its own React rather than using the provided version?

**Comment by john-osullivan** [comment]
Did some more debugging after an outside click produced this error:
```
TypeError: Cannot read property 'contains' of null
```
It turns out to have originated within the `handleOutsideClick` method in `portal.js` as a result of these lines of code:
```
var root = (0, _reactDom.findDOMNode)(this.portal);
      if (root.contains(e.target) || e.target.tagName === 'HTML') {
        return;
      }
```
I'm not certain enough about what's going on here to say for sure, but it does look like the actual portal (`this.portal`) isn't getting made in the same React as everything else is being done in.  The docs said it gets made in a new React tree, but it's still the same actual React instance, right?

**Comment by PeteJodo** [comment]
I know that `this.portal` can be `null` in its closed states. Can you check if `this.portal` is `null` in your case because then it could be something that puts it in a weird state where that fires but the portal is closed? How do you repro?

**Comment by tajo** [comment]
> The docs said it gets made in a new React tree, but it's still the same actual React instance, right?

Yes. But even if you have two React instances running, it should be fine in this case, since the new React tree is independent/next to the original React tree, therefore there is no clashing between them.

What's your render target for the main (original) React tree? **It should never be document.body** because some other libraries (independent on React) can append there some mess that makes React crazy. Also, it would conflict with react-portal.

**Comment by greenimpala** [comment]
Can confirm this is happening to me. React is being rendered into a `div#root` as standard. I am using Webpack for build. When clicking outside `this.portal` seems to be null and throws an error!
