### ISSUE TITLE
Add onClose() hook

### ISSUE THREAD

**Issue by moroshko** [tajo/react-portal#4]
Is there a way to execute something when modal is closed?
I have the following scenario:
1. User clicks the Help button which opens a modal dialog
2. User closed the modal dialog
3. At this stage, I'd like to set the focus back to the Help button.
This is the desired behaviour according to the [WAI-ARIA spec](http://www.w3.org/TR/wai-aria-practices/#dialog_modal):
> When the dialog is closed or cancelled focus should return to the element in the application which had focus before the dialog is invoked. This is usually the control which opened the dialog.

It would be great to have an `onClose()` hook to be able to create more accessible components.

**Comment by tajo** [comment]
`onClose()` makes perfect sense even for other scenarios. (The focus to the control which opened the portal can be set automatically) . Your pull request will be welcome :-)

**Comment by moroshko** [comment]
[Here you go](https://github.com/tajo/react-portal/pull/6)

**Comment by tajo** [comment]
Thank you! Published as `v0.4.1`.
