### ISSUE TITLE
Redbox dependency in 1.5.4

### ISSUE THREAD

**Issue by thebuilder** [tajo/react-portal#41]
Trying to import the node module, throws the following error:

```
 Cannot find module '/Users/miksu/Projects/react-portal/node_modules/redbox-react/lib/index.js' from '../node_modules/react-portal/build'
```

**Comment by A11oW** [comment]
+1

**Comment by tajo** [comment]
Fixed and released as `v1.5.5`. I'm really sorry for that.

**Comment by PeteJodo** [comment]
You may want to consider unpublishing `v1.5.4` from npm

**Comment by tajo** [comment]
I would have to unpublish also `v1.5.1`, `v1.5.2` and `v1.5.3`. The same bug. Not sure if it's good idea. The number of affected people should be very small since I made all these releases just in last 12 hours.

**Comment by tajo** [comment]
I unpublished broken `v1.5.1` - `v.1.5.4` releases.
