### ISSUE TITLE
"Animation example" does nothing

### ISSUE THREAD

**Issue by polkovnikov-ph** [tajo/react-portal#42]
in a demo, click on "Animation example" doesn't show anything up.

**Comment by Fofir** [comment]
+1

**Comment by tajo** [comment]
Thanks. It's fixed by https://github.com/tajo/react-portal/commit/b54ead88d0f6869ef6864a9c4d5f7d0d2bba902f

**Comment by polkovnikov-ph** [comment]
Okay, let's find another bug :)
