### ISSUE TITLE
Props for children element

### ISSUE THREAD

**Issue by azranel** [tajo/react-portal#43]
Hey
Im using this library and have a little problem with passing props to children. Take this code for example:

```html
<Portal openByClickOn={ this.props.children }>
      <Body application={ this.props.application } />
</Portal>
```

`this.props.application` is not undefined but when I click element passed in `openByClickOn`, `Body` component have undefined as params. Any idea how to handle that? :smile:

**Comment by tajo** [comment]
Working example?

**Comment by azranel** [comment]
Okay, sorry for issue, problem like most of the times is between chair and computer. :smile: Was rendering the same component depending on the viewport but did pass props only to one of those versions.
