### ISSUE TITLE
Passing styles to the wrapper div

### ISSUE THREAD

**Issue by neglectedvalue** [tajo/react-portal#44]
Hi, guys!
I struggled into a problem. I have a group of inlined buttons, and one of them opens a modal window.
The problem that the react-portal wraps a button into the `div`, so the markup becomes broken.
Is there a way to pass styles or add an additional class to the wrapper `div`?
Also, is it possible to change the wrapper `div` to the `span`?

**Comment by tajo** [comment]
this https://github.com/tajo/react-portal/pull/40

**Comment by tajo** [comment]
https://github.com/tajo/react-portal/pull/40 merged.
