### ISSUE TITLE
onClose triggered 2 times

### ISSUE THREAD

**Issue by Sinewyk** [tajo/react-portal#45]
When we use the closePortal props passed to the children (https://github.com/tajo/react-portal/blob/master/lib/portal.js#L87) it immediately triggers the `onClose` props (https://github.com/tajo/react-portal/blob/master/lib/portal.js#L87).

Because we unmount the portal when we receive the onClose we actually trigger the `onClose` two times because of the second one coming of course from the componentWillUnmount lifecycle (https://github.com/tajo/react-portal/blob/master/lib/portal.js#L69).

Do we misuse this library or should we try to make it so that react-portal can only call the onClose callback once ?

edit: clarity of last phrase

**Comment by tajo** [comment]
> Because we unmount the portal when we receive the onClose

You should always leave the unmounting to library. If you need to do some async thing (like fading off animation) and then unmount it, use `beforeClose` callback and call removeFromDOM after.

**Comment by Sinewyk** [comment]
I do not manually unmount the portal. I mean that my render function is like
```javascript
getInitialState() { return { condition: true }; }
onClose() {
  // called two times, via closePortal props passed via clone element,
  // and because I unmount the portal
  this.setState({ condition: false });
}
render() {
  return <div>
    { this.state.condition ? <Portal show onClose={this.onClose}>
      <... /* Something that can call closePortal *//>
    </Portal> : null }
  </div>;
}
```

so ... for you that would be wrong ? I should always actually *mount* the Portal but control it via the show property (remove the condition between `<Portal/>` and `null` and just pass the condition to show ? and not actually unmounting it ?

**Comment by tajo** [comment]
What's the prop `show`? Do you mean `isOpened`? Since the Portal component alone actually renders null (https://github.com/tajo/react-portal/blob/master/lib/portal.js#L94), there should be no need to ever do this `{ this.state.condition ? <Portal...`

However, when you use `isOpened` instead of `openByClickOn`, it's up to you to control opening/closing of the portal and `this.props.closePortal` is useless then.

Maybe you want to do something like this
```js
render() {
  return <div>
    <Portal isOpened={this.state.condition} onClose={this.onClose}>
      <... /* Can't use closePortal, just do this.state.condition = false *//>
    </Portal>
  </div>;
}
```

**Comment by Sinewyk** [comment]
I meant `isOpened` my bad. Ok. So I should never actually conditionally render the portal, and let the library do it for me.

But then there's still the matter of like navigating away from the page. The onClose will be called when the portal may have been closed a long time ago no ?

**Comment by tajo** [comment]
> I meant isOpened my bad. Ok. So I should never actually conditionally render the portal, and let the library do it for me.

Yes. 

> But then there's still the matter of like navigating away from the page. The onClose will be called when the portal may have been closed a long time ago no ?

Yes. Now, it's always called when the main component is unmounted. This behavior is probably a bug (doesn't make sense to me). @moroshko implemented it though, any thoughts?

**Comment by Sinewyk** [comment]
Tried fixing it there https://github.com/tajo/react-portal/pull/48.

Let me know what you think.
