### ISSUE TITLE
Click outside in the demo doesn't handle part of the page

### ISSUE THREAD

**Issue by polkovnikov-ph** [tajo/react-portal#49]
When clicking on the bottom part of the screen, "click outside" functionality doesn't work, apparently due to handling of the bubbling events up to `<body>` (that can take only a part of the screen) while it's properly done up to `<html>`.

**Comment by tajo** [comment]
Can you please fix it (send a PR)? Thanks.

**Comment by tajo** [comment]
fixed `v2.1.0`
