### ISSUE TITLE
react-portal for React 15.0.0-rc.1

### ISSUE THREAD

**Issue by slorber** [tajo/react-portal#58]
Hi,

Can you make the library compatible with 15.0.0-rc.1 plz? :)

**Comment by bkniffler** [comment]
:+1:

**Comment by tajo** [comment]
I might release v3-rc1 version this weekend.

**Comment by tajo** [comment]
peerDeps were removed (https://github.com/tajo/react-portal/pull/59) and everything else seems to be working with `15.0.0-rc.1` just fine, although there is one test failing but it looks like a enzyme problem - I'll fix it later

**Comment by slorber** [comment]
thanks
