### ISSUE TITLE
`isOpened` to `isOpen`

### ISSUE THREAD

**Issue by ianstormtaylor** [tajo/react-portal#61]
Just a random thing I noticed, might be nicer to call it `isOpen`, since React is stateless, so everything should really be in the present tense.

**Comment by dlindenkreuz** [comment]
@tajo, can you please assess this issue? `isOpened` breaks the convention @ianstormtaylor described and does not sound correct linguistically.

**Comment by tajo** [comment]
If you create a PR with a deprecation notice (including README), I'll merge it into another major version.

**Comment by dlindenkreuz** [comment]
Done!
