### ISSUE TITLE
mimic react lifecycle props with `on*` handlers

### ISSUE THREAD

**Issue by ianstormtaylor** [tajo/react-portal#62]
Right now the handlers are defined as:

- `onOpen`
- `onClose`
- `onBeforeClose`

It could be nice to mimic the React lifecycle method naming, to make it more clear right away:

- `onWillMount` (would be as if there was a `onBeforeOpen` right now)
- `onDidMount` (aka `onOpen`)
- `onWillUnmount` (aka `onBeforeClose`)
- `onDidUnmount` (aka `onClose`)

**Comment by tajo** [comment]
Yeah, it would make more sense but it's not worth of the trouble for now.
