### ISSUE TITLE
Call onClose when closeOnEsc is true

### ISSUE THREAD

**Issue by pradel** [tajo/react-portal#63]
I was wondering maybe it's better to call onClose when you set closeOnEsc prop, because the parent don't know the modal is close when you press esc key.
Do you want a PR for that ?

**Comment by tajo** [comment]
I don't follow. When you press esc key, onClose is called, right?

**Comment by pradel** [comment]
No it is not called.

**Comment by tajo** [comment]
```jsx
<Portal closeOnEsc openByClickOn={button1} onClose={() => console.log('closed')}>
   // ...
</Portal>
```

ESC prints closed into the console.

**Comment by pradel** [comment]
Maybe I miss something I will try again thanks !
