### ISSUE TITLE
Clicking on "openByClickOn" element causes portal to hide and then immediately show.

### ISSUE THREAD

**Issue by sam-aiq** [tajo/react-portal#65]
When the prop `closeOnOutsideClick` is true, clicking on the `openByClickOn` element causes the portal to hide, and then immediately show.

**Comment by tajo** [comment]
Yeah, that's a glitch. Do you want to create a PR? It should be simple.

**Comment by oldboyxx** [comment]
Replace mousedown events with mouseup.

**Comment by Sediug** [comment]
That's an awesome component. It will be very useful for my projects. Thanks very much! @tajo

**Comment by tajo** [comment]
fixed in `v2.1.1`

**Comment by Hypnosphi** [comment]
I have the same issue in 3.0.0
Maybe you should check here that e.target isn't the openByClickOn element or its child
https://github.com/tajo/react-portal/blob/master/lib/portal.js#L111

**Comment by Hypnosphi** [comment]
And I quess that most people would like the portal to hide in this case, not to keep being shown
