### ISSUE TITLE
Duplicated document events when having multiple portal components

### ISSUE THREAD

**Issue by oldboyxx** [tajo/react-portal#66]
Try including multiple portals on your page and then put a console log inside 'handleOutsideMouseClick' method. It triggers once for every portal.

So if I have a list of 100 items each wrapped in a portal, the event will trigger 100 times in a row when clicking on one item.

Solution: put addEventListeners inside 'openPortal' and  removeEventListeners inside  'closePortal' instead of compDidMount/willUnmount

**Comment by tajo** [comment]
Great idea! Do you want to create a PR?

**Comment by oldboyxx** [comment]
False alarm. I made a mistake while fiddling with code.
