### ISSUE TITLE
isOpened variable is not set to true on closeOnOutsideClick

### ISSUE THREAD

**Issue by FezVrasta** [tajo/react-portal#69]
I'm manually managing the state of the portal using `isOpened`

```
<span>
  {button}
  <Portal closeOnEsc closeOnOutsideClick isOpened={this.state.isOpened}>
    <div styleName='popover' ref='popover'>
      {arrow}
      {this.props.popover}
    </div>
  </Portal>
</span>
```

The problem is that when I click outside, the portal is closed, bu the `this.state.isOpened` prop is not set to false.
I'm I missing something?

**Comment by Sediug** [comment]
You need to update the prop yourself, you can't pretend a component update it's own props. If you need to do that you can fork the project and add a prop that's a callback function for when Portal get closed by clicking outside. With that you can update the parent components. You can modify the handleOutsideMouseClick function. 

 handleOutsideMouseClick(e) {
    if (!this.state.active) { return; }

    const root = findDOMNode(this.portal);
    if (root.contains(e.target) || (e.button && e.button !== 0)) { return; }

    e.stopPropagation();
// NEW CODE HERE
if (typeof this.props.isOpened !== 'undefined' && this.props.yourCallBackFunction) {
    this.props.yourCallBackFunction.call(this, false);
}
// END NEW CODE
    this.closePortal();
  }

So in the parent you must have your function:

yourCallBackFunction(isOpened) {
    this.setState({isOpened: isOpened});
}

<Portal
....
yourCallBackFunction = {this.yourCallBackFunction}
...
>
{children}
</Portal>

Same for handleKeydown if you want.

**Comment by FezVrasta** [comment]
I see, thanks for the great component!
