### ISSUE TITLE
Portal used in iframe is transported to top-level document rather than frame document

### ISSUE THREAD

**Issue by matthewgertner** [tajo/react-portal#73]
I am using a `<Portal>` inside a frame, and I expected the element to be added as a child of the frame document's body. Instead, it is added as a child of the top-level document's body. I guess this could be fixed by having `render` return something like `<noscript ref="root">` instead of `null` and then using `this.refs.root.ownerDocument` everywhere that `document` is used currently.

**Comment by tajo** [comment]
👍 PR?
