### ISSUE TITLE
Callbacks for closeOnEsc and closeOnOutsideClick

### ISSUE THREAD

**Issue by jeffijoe** [tajo/react-portal#75]
When in controlled mode (using `isOpened`), we loose `closeOnEsc` and `closeOnOutsideClick`

I'm proposing a `onRequestClose` callback to be used when in controlled state. That will give the consumer a chance to update state without having to reimplement esc-closing, etc.

**Comment by tajo** [comment]
Yea, it's a legit idea. I liked this proposal: https://github.com/tajo/react-portal/issues/51 (it goes deeper)
