### ISSUE TITLE
openByClickOn element does not accept styles - CSS Modules

### ISSUE THREAD

**Issue by karthikiyengar** [tajo/react-portal#84]
Hi,

Thanks for the nice library. I'm using CSS Modules + React CSS Modules. The element I pass to 'openByClickOn' does not render with styles assigned to it.

The default React properties className and style on the element seem to work fine and the element is rendered with appropriate styles. Using the styleName syntax does not seem to work for this element.

`		const link = (
			<span styleName="link">
				Set
			</span>
		);
`

I've not gone through the source, but would it be possible not have the element rendered by the Portal component and let the user explicitly provide/render his own? Working around this by managing the state myself.

**Comment by tajo** [comment]
> I've not gone through the source, but would it be possible not have the element rendered by the Portal component and let the user explicitly provide/render his own? **Working around this by managing the state myself.**

Yes, you can use the prop `isOpened : bool`.
