### ISSUE TITLE
PseudoModal is not defined

### ISSUE THREAD

**Issue by ibiza240** [tajo/react-portal#88]
I get an `Uncaught ReferenceError: PseudoModal is not defined` exception when I try a Hello World first test...Here is the browser console output, we can see that it did not parse the PseudoModal JSX tag :

```
        _react2['default'].createElement(
            PseudoModal,
            null,
            _react2['default'].createElement(
                'div',
                { id: 'div' + username, className: 'on-top fadeInDown' },
                _react2['default'].createElement('br', null),
                _react2['default'].createElement('br', null),
                'Thank you '
            )
```

Also, I find no match for `PseudoModal` from a search in the portal.js source code.

What am I missing?

Thank you, it looks great!

<hr />

edit: Also, while posting here :) ...is there a way to close after a set amount of time?

I think it would be something like this:

```
    var divModal = (
        <Portal>
                <div>Hello</div>
        </Portal>);

    setTimeout(function() {
        divModal.closePortal();
    }, 12000);
```

but then how to initialize the instance of the portal..? I se only `openByClick`, is there a way to launch a new instance while in a javascript function?

Thanks!

**Comment by VolCh** [comment]
PseudoModal as class is your own component that rendered by Portal. 'PseudoModal' as name is an example name, it may be common Modal, Dialog, Window or more specifier ConfirmMyEntitySave, MyCoolAlert an do so on.
