### ISSUE TITLE
onOpen fires after onUpdate for the first render

### ISSUE THREAD

**Issue by ianstormtaylor** [tajo/react-portal#90]
Using a simple portal of:

``` js
<Portal
  isOpened
  onOpen={() => console.log('onOpen')}
  onUpdate={() => console.log('onUpdate')}
/>
```

You'll see in your console:

```
onUpdate
onOpen
```

Instead of the expected:

```
onOpen
```

The docs make it seem like `onUpdate` is similar to `componentDidUpdate`, but it seems like it's not...

**Comment by tajo** [comment]
I merged https://github.com/tajo/react-portal/pull/92 that fixes the order of

```
onUpdate
onOpen
```

to 

```
onOpen
onUpdate
```

I know that it seems similar to `componentDidUpdate` but I don't see a value in changing this right now. Also, I feel it's more practical to call `onUpdate` with opening for majority of use-cases.
