### ISSUE TITLE
How to do CSS transitions by appending a className on portal or child after open?

### ISSUE THREAD

**Issue by HriBB** [tajo/react-portal#93]
Hello

I am having some hard time figuring out how to do a simple CSS transitions with `react-portal`.

I have a `button` that opens a `menu` and I want to append a `menu-open` className to portal or child after they are opened. I tried with `onOpen` callback to `setState({ open: true })` then passing the `open` as a prop to child, but the it never updates. After reading the source code I figured that this wont work. I know I could update DOM node `style` property, but I want to control animations by appending/removing classes. What is the proper way to do this with `react-portal`?

Some code, just for reference :)

So this does not work, `MenuList` is never updated with `isOpen=true`

```
export default class Menu extends Component {

  static propTypes = {
    children: PropTypes.any.isRequired,
    target: PropTypes.element.isRequired,
  }

  constructor(props) {
    super(props)
    this.state = { open: false }
    this.onOpen = () => this.setState({ open: true })
    this.onClose = () => this.setState({ open: false })
  }

  render() {
    const { children, target } = this.props
    const { open } = this.state
    return (
      <Portal
        className={'bit-menu__portal'}
        onOpen={this.onOpen}
        onClose={this.onClose}
        closeOnEsc
        closeOnOutsideClick
        openByClickOn={target}
      >
        <MenuList isOpen={open}>
          {this.props.children}
        </MenuList>
      </Portal>
    )
  }

}
```

Easy workaround is to add a `setTimeout()` in child `componentDidMount`, but I don't like this solution.

```
class MenuList extends Component {

  static propTypes = {
    children: PropTypes.any.isRequired,
    className: PropTypes.string,
    closePortal: PropTypes.func,
  }

  constructor(props) {
    super(props)
    this.state = { open: false }
  }

  componentDidMount() {
    setTimeout(() => {
      this.setState({ open: true })
    }, 10)
  }

  render() {
    const { children, className, closePortal, ...rest } = this.props
    const menuClass = classnames('bit-menu', {
      'bit-menu--open': this.state.open
    }, className)
    return (
      <ul className={menuClass} {...rest}>
        {Children.map(children, child =>
          cloneElement(child, { closePortal }
        ))}
      </ul>
    )
  }
}
```

**Comment by TrevorHinesley** [comment]
@HriBB how did you resolve this?

**Comment by HriBB** [comment]
I am doing animation manually, because you can't control portal `node` with react.

**Comment by jcrben** [comment]
If you can update the `style` property of the node, it seems like can remove/add classes just as easily. From there you can listen to `animationend`. But I'm trying to figure out how to do it in more of a React `CSSTransitionGroup` way...

**Comment by onzag** [comment]
How is this solved? The children won't update, I can't call this a fix.
