### ISSUE TITLE
isOpened should work with any truthy value

### ISSUE THREAD

**Issue by willdady** [tajo/react-portal#94]
Currently isOpened is expected to be a boolean which is too strict.

`Failed prop type: Invalid prop 'isOpened' of type 'object' supplied to 'Portal', expected 'boolean'.`

This should be relaxed so that **any** truthy value works.

**Comment by Andreyco** [comment]
In my honest opinion, existing propType check for `isOpened` is the best possible.

Isn't this sufficient fix for your use case?
```jsx
<Portal isOpened={!!this.props.anyObject} />
// where:
// !!{} => true
// !!'0' => true
// ...
```
