### ISSUE TITLE
`onClose` called when it should not be called

### ISSUE THREAD

**Issue by Andreyco** [tajo/react-portal#95]
Consider this implementation

``` js
import React, { Component, PropTypes } from "react";
import Portal from 'react-portal';

export default class Button extends Component {
    state = {
        portalIsOpened: false,
    }

    onClose = () => {
        console.log('on close');
    }

    beforeClose = (node, resetPortalState) => {
        console.log('before close');
    }

    render() {
        return (
            <Portal
                beforeClose={this.beforeClose}
                onClose={this.onClose}
                closeOnEsc
                closeOnOutsideClick
                isOpened={this.state.portalIsOpened}
            >
                <div>
                    <h2>Pseudo Modal</h2>
                    <p>This react component is appended to the document body.</p>
                </div>
            </Portal>
        );
    }
}
```

Element in portal should be closed if user presses ESC key or clicks outside. 
Having above implementation, I decide when to close portal. In order to close portal manually I receive `resetPortalState` callback.

Use Case
- Open portal and press ESC to close it
- Actual Console output

```
"before close"
"on close"
```
- Expected Console output

```
"before close"
```

The issue is `onClose` is triggered even if portal is not actually closed.

`onClose` should be closed only and after `resetPortalState` is invoked and "done".

**Comment by tajo** [comment]
I'm planning to merge https://github.com/tajo/react-portal/pull/96 that solves this. Closing this issue to cleanup.
